name: Deploy UserAPI

on:
  push:
    branches:
      - main
    paths:
      - 'UserAPI/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Publish project
        run: dotnet publish src/UserAPI/UserAPI.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: smart-userapi-dev
          publish-profile: ${{ secrets.AZURE_USERAPI_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/app
