name: Deploy NotificationAPI

on:
  push:
    branches:
      - main
    paths:
      - 'NotificationAPI/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Publish project
        run: dotnet publish NotificationAPI -c Release -o ${{env.DOTNET_ROOT}}/app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: smart-notificationapi-dev
          publish-profile: ${{ secrets.AZURE_NOTIFICATIONAPI_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/app
